version: '3.8'

services:

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: michal
      POSTGRES_PASSWORD: haslo_do_PSQL
    ports:
    - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_manager
      SPRING_DATASOURCE_USERNAME: michal
      SPRING_DATASOURCE_PASSWORD: haslo_do_PSQL
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
